In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("gpu is avilable!")
  print(f"Using gpu: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avilable.Using CPU.")

gpu is avilable!
Using gpu: Tesla T4


# Cretaing a Tensor

In [ ]:
# using empty
a=torch.empty(2,3)

In [ ]:
# chek types
type(a)


torch.Tensor

In [ ]:
# using zeroes
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.8211, 0.8543, 0.0219],
        [0.8639, 0.4313, 0.2385]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.5910, 0.5354, 0.0209],
        [0.8240, 0.1867, 0.2092]])

In [ ]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

In [ ]:
# arange
print("using arange ->",torch.arange(0,10,2))

# using linspace
print("using linspace ->",torch.linspace(0,10,10))

# using eye
print("using eye ->",torch.eye(5))

# using full
print("using full ->",torch.full((2,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


# Tensor Shapes

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067810143170473270, 3545241310312674609],
        [6501005655606113582, 7309453675965983778, 8315168162784306286]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# Tensor data types

In [ ]:
# find data types
x.dtype

torch.int64

In [ ]:
# assign  data types
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)


tensor([[1., 2., 3.],
        [4., 5., 6.]])

# Mathemtical operations

In [ ]:
1 # scalar operation
x=torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
# addition
x+2
# substraction
x-2
# multiplication
x*3
# division
x/3
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

# Element wise operations


In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014]])
tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])


In [ ]:
# add
a+b
# sub
a-b
# multiply
a*b
# division
a/b
# power
a**b
# mod
a%b

tensor([[0.1217, 0.7356, 0.0401],
        [0.1829, 0.0615, 0.0776]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# flor
torch.floor(d)


tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d,min=2,max=3)


tensor([2.0000, 2.3000, 3.0000, 3.0000])

# Reducation opeation


In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[4., 6., 0.],
        [1., 9., 9.]])

In [ ]:
# sum
torch.sum(e)

tensor(29.)

In [ ]:
# sum along columns
torch.sum(e,dim=0)

tensor([ 5., 15.,  9.])

In [ ]:
# sum along rows
torch.sum(e,dim=1)

tensor([10., 19.])

In [ ]:
# mean
torch.mean(e)

tensor(4.8333)

In [ ]:
# mean along columns
torch.mean(e,dim=0)

tensor([2.5000, 7.5000, 4.5000])

In [ ]:
# mean along rows
torch.mean(e,dim=1)

tensor([3.3333, 6.3333])

In [ ]:
# median
torch.median(e)

tensor(4.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(0.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.8687)

In [ ]:
# variance
torch.var(e)

tensor(14.9667)

In [ ]:
# argmax
torch.argmax(e)

tensor(4)

In [ ]:
# argmin
torch.argmin(e)

tensor(2)

# matrix operations

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[8, 0, 7],
        [0, 0, 9]])
tensor([[5, 7],
        [3, 9],
        [4, 0]])


In [ ]:
# matrix multiplaction
torch.matmul(f,g)

tensor([[68, 56],
        [36,  0]])

In [ ]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[8, 0],
        [0, 0],
        [7, 9]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10)
h

tensor([[0, 8, 4],
        [7, 2, 3],
        [8, 5, 6]])

In [ ]:
# determinant
torch.det(h.to(torch.float32))

tensor(-68.0000)

In [ ]:
# inverse
torch.inverse(h.to(torch.float32))

tensor([[ 0.0441,  0.4118, -0.2353],
        [ 0.2647,  0.4706, -0.4118],
        [-0.2794, -0.9412,  0.8235]])

# 5 Comparsion Operations

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)


tensor([[2, 9, 5],
        [0, 4, 2]])
tensor([[7, 1, 1],
        [5, 4, 4]])


In [ ]:
# greater than
i>j

# less than
i<j

# equal to
i==j

# not equal to
i!=j

# greater than equal to
i>=j

# less than equal to
i<=j

tensor([[True, True, True],
        [True, True, True]])

# Special function


In [ ]:
k=torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)
k

tensor([[5., 6., 1.],
        [4., 5., 6.]])

In [ ]:
# log
torch.log(k)

tensor([[1.6094, 1.7918, 0.0000],
        [1.3863, 1.6094, 1.7918]])

In [ ]:
# exp
torch.exp(k)

tensor([[148.4132, 403.4288,   2.7183],
        [ 54.5981, 148.4132, 403.4288]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.4495, 1.0000],
        [2.0000, 2.2361, 2.4495]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.9975, 0.7311],
        [0.9820, 0.9933, 0.9975]])

In [ ]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.7311, 0.7311, 0.0067],
        [0.2689, 0.2689, 0.9933]])

# inplace operations

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.3079, 0.6269, 0.8277],
        [0.6594, 0.0887, 0.4890]])
tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])


In [ ]:
m.add_(n)

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [ ]:
m

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [ ]:
n

tensor([[0.5887, 0.7340, 0.8497],
        [0.9112, 0.4847, 0.9436]])

In [ ]:
torch.relu(m)

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [ ]:
m.relu_()

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

In [ ]:
m

tensor([[0.8966, 1.3610, 1.6774],
        [1.5705, 0.5734, 1.4325]])

# copying a tensor

In [ ]:
a=torch.rand(2,3)

In [ ]:
a

tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
b=a

In [ ]:
b

tensor([[0.3904, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
b

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
id(a)

138665221778928

In [ ]:
id(b)

138665221778928

In [ ]:
b=a.clone()

In [ ]:
a

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
b

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
a[0][0]=10

In [ ]:
a

tensor([[10.0000,  0.2499,  0.3206],
        [ 0.9753,  0.7582,  0.6688]])

In [ ]:
b

tensor([[0.0000, 0.2499, 0.3206],
        [0.9753, 0.7582, 0.6688]])

In [ ]:
id(a)

138665221778928

In [ ]:
id(b)

138665221966896

# Tensor Operations on gpu

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating a new tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
# moving an existing tensor to gpu
a=torch.rand(2,3)

In [ ]:
a

tensor([[0.2651, 0.2336, 0.5057],
        [0.5688, 0.0634, 0.8993]])

In [ ]:
b=a.to(device)

In [ ]:
b+5

tensor([[5.2651, 5.2336, 5.5057],
        [5.5688, 5.0634, 5.8993]], device='cuda:0')

# Reshping Tensors

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])